require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  NewCops: enable

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - config/{application,boot,environment}.rb
    - config/environments/*.rb
    - config/initializers/*.rb

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - config/{application,boot,environment}.rb
    - config/environments/*.rb

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/EnvironmentVariableAccess:
  Exclude:
    - lib/*/**

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
