services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      POSTGRES_PASSWORD: postgres
      SELENIUM_REMOTE: '1'
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  
  db:
    image: postgres:latest
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vscode
      POSTGRES_PASSWORD: postgres

  selenium:
    image: selenium/standalone-chrome:latest
    network_mode: service:app

volumes:
  postgres-data:
