name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ruby/setup-ruby@v1.237.0
        with:
          bundler-cache: true

      - run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ruby/setup-ruby@v1.237.0
        with:
          bundler-cache: true

      - run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ruby/setup-ruby@v1.237.0
        with:
          bundler-cache: true

      - uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: yarn

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: bin/rails db:create ridgepole:apply spec
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
