name: Ruby

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']

    env:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4.1.4

      - uses: ruby/setup-ruby@v1.175.1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '22'
          cache: yarn

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Setup database
        run: |
          bin/rake db:create
          bin/rake ridgepole:apply

      - name: Run the default task
        run: bin/rake
